### PR TITLE
Pr for benchmark.py update on multiple hashcat algorithm and multiple GPU

### PR DESCRIPTION
**Pull request by thomas-chu123**
Enhance the multiple GPU and random algorithm on benchmark testing script.
1. Support Blake2b-512, Scrypt, SHA2-256, SHA2-386, SHA2-512, SAP CODVN F/G (PASSCODE), Ruby on Rail authentication.
2. Add the threading for the hashcat function.
3. Add the multiple GPU hashcat loading sharing function.
4. Add the option to select the random algorithm in the menu.
5. Update the output summary for multiple GPU

### CODE REVIEW

**Comment by rycao18** [comment]
While this is interesting, why did you add support for other hashing functions?

**Comment by thomas-chu123** [comment]
The multiple hashcat algorithm can be used to check which algorithm will provide the best fair algorithm to validate the miner.

**Comment by rycao18** [comment]
Yea but it’s a miner sided benchmark and I don’t see the results being sent anywhere, and the only benchmark that compute subnet uses right now is 610

**Review by edpoptart — APPROVED** [review]
Looks good

**Comment by donjmilligan** [comment]
Hi guys, @rycao18 @thomas-chu123 Can we get some clarification on this conversation? AFAIK we needed more than one type of test to pass to the miners since some miners are capable of doing exceedingly well at some types of benchmarks. Literally the reason we hired Thomas was to bring in more than one type of benchmark, and his job was to figure out which ones to use.

I'd like to know if this PR is still valid, and whether it's still compatible with the latest release.

**Pull request closed without merging**
